Add test-case for #243
in test/2-config-test.js, added to the section "Comfiguration for module developers".
Testcase shows,  that calling ".get" on a moduleConfig received by a previous .get call will throw a TypeError for "unknown is not a function" if ithe moduleConfig was added solely by "setModuleDefautlts".